version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: url_shortener_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - url_shortener_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortener_app
    ports:
      - "3000:3000"
      - "9229:9229" #debug port
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - url_shortener_network

volumes:
  postgres_data:

networks:
  url_shortener_network:
    driver: bridge